<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum AdjustmentType: int
{
    /** 0x00000001 */
    case Increment = 1;

    /** 0x00000002 */
    case Decrement = 2;

    /** 0x00000003 */
    case Negate = 3;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Increment => 'Increment',
            self::Decrement => 'Decrement',
            self::Negate => 'Negate',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
