<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum AsynchronousIndicator: int
{
    /** 0x00000001 */
    case Mandatory = 1;

    /** 0x00000002 */
    case Optional = 2;

    /** 0x00000003 */
    case Prohibited = 3;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Mandatory => 'Mandatory',
            self::Optional => 'Optional',
            self::Prohibited => 'Prohibited',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
