<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum AttestationType: int
{
    /** 0x00000001 */
    case TPMQuote = 1;

    /** 0x00000002 */
    case TCGIntegrityReport = 2;

    /** 0x00000003 */
    case SAMLAssertion = 3;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::TPMQuote => 'TPM Quote',
            self::TCGIntegrityReport => 'TCG Integrity Report',
            self::SAMLAssertion => 'SAML Assertion',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
