<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum BatchErrorContinuationOption: int
{
    /** 0x00000001 */
    case Continue = 1;

    /** 0x00000002 */
    case Stop = 2;

    /** 0x00000003 */
    case Undo = 3;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Continue => 'Continue',
            self::Stop => 'Stop',
            self::Undo => 'Undo',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
