<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum BlockCipherMode: int
{
    /** 0x00000001 */
    case CBC = 1;

    /** 0x00000002 */
    case ECB = 2;

    /** 0x00000003 */
    case PCBC = 3;

    /** 0x00000004 */
    case CFB = 4;

    /** 0x00000005 */
    case OFB = 5;

    /** 0x00000006 */
    case CTR = 6;

    /** 0x00000007 */
    case CMAC = 7;

    /** 0x00000008 */
    case CCM = 8;

    /** 0x00000009 */
    case GCM = 9;

    /** 0x0000000A */
    case CBCMAC = 10;

    /** 0x0000000B */
    case XTS = 11;

    /** 0x0000000C */
    case AESKeyWrapPadding = 12;

    /** 0x0000000D */
    case NISTKeyWrap = 13;

    /** 0x0000000E */
    case X9_102AESKW = 14;

    /** 0x0000000F */
    case X9_102TDKW = 15;

    /** 0x00000010 */
    case X9_102AKW1 = 16;

    /** 0x00000011 */
    case X9_102AKW2 = 17;

    /** 0x00000012 */
    case AEAD = 18;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::CBC => 'CBC',
            self::ECB => 'ECB',
            self::PCBC => 'PCBC',
            self::CFB => 'CFB',
            self::OFB => 'OFB',
            self::CTR => 'CTR',
            self::CMAC => 'CMAC',
            self::CCM => 'CCM',
            self::GCM => 'GCM',
            self::CBCMAC => 'CBC-MAC',
            self::XTS => 'XTS',
            self::AESKeyWrapPadding => 'AESKeyWrapPadding',
            self::NISTKeyWrap => 'NISTKeyWrap',
            self::X9_102AESKW => 'X9.102 AESKW',
            self::X9_102TDKW => 'X9.102 TDKW',
            self::X9_102AKW1 => 'X9.102 AKW1',
            self::X9_102AKW2 => 'X9.102 AKW2',
            self::AEAD => 'AEAD',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
