<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum CancellationResult: int
{
    /** 0x00000001 */
    case Canceled = 1;

    /** 0x00000002 */
    case UnableToCancel = 2;

    /** 0x00000003 */
    case Completed = 3;

    /** 0x00000004 */
    case Failed = 4;

    /** 0x00000005 */
    case Unavailable = 5;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Canceled => 'Canceled',
            self::UnableToCancel => 'Unable to Cancel',
            self::Completed => 'Completed',
            self::Failed => 'Failed',
            self::Unavailable => 'Unavailable',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
