<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum CertificateType: int
{
    /** 0x00000001 */
    case X_509 = 1;

    /** 0x00000002 */
    case PGP = 2;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::X_509 => 'X.509',
            self::PGP => 'PGP',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
