<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum ClientRegistrationMethod: int
{
    /** 0x00000001 */
    case Unspecified = 1;

    /** 0x00000002 */
    case ServerPreGenerated = 2;

    /** 0x00000003 */
    case ServerOnDemand = 3;

    /** 0x00000004 */
    case ClientGenerated = 4;

    /** 0x00000005 */
    case ClientRegistered = 5;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Unspecified => 'Unspecified',
            self::ServerPreGenerated => 'Server Pre-Generated',
            self::ServerOnDemand => 'Server On-Demand',
            self::ClientGenerated => 'Client Generated',
            self::ClientRegistered => 'Client Registered',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
