<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum CredentialType: int
{
    /** 0x00000001 */
    case UsernameAndPassword = 1;

    /** 0x00000002 */
    case Device = 2;

    /** 0x00000003 */
    case Attestation = 3;

    /** 0x00000004 */
    case OneTimePassword = 4;

    /** 0x00000005 */
    case HashedPassword = 5;

    /** 0x00000006 */
    case Ticket = 6;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::UsernameAndPassword => 'Username and Password',
            self::Device => 'Device',
            self::Attestation => 'Attestation',
            self::OneTimePassword => 'One Time Password',
            self::HashedPassword => 'Hashed Password',
            self::Ticket => 'Ticket',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
