<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum DerivationMethod: int
{
    /** 0x00000001 */
    case PBKDF2 = 1;

    /** 0x00000002 */
    case HASH = 2;

    /** 0x00000003 */
    case HMAC = 3;

    /** 0x00000004 */
    case ENCRYPT = 4;

    /** 0x00000005 */
    case NIST800108C = 5;

    /** 0x00000006 */
    case NIST800108F = 6;

    /** 0x00000007 */
    case NIST800108DPI = 7;

    /** 0x00000008 */
    case AsymmetricKey = 8;

    /** 0x00000009 */
    case AWSSignatureVersion4 = 9;

    /** 0x0000000A */
    case HKDF = 10;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::PBKDF2 => 'PBKDF2',
            self::HASH => 'HASH',
            self::HMAC => 'HMAC',
            self::ENCRYPT => 'ENCRYPT',
            self::NIST800108C => 'NIST800 - 108 - C',
            self::NIST800108F => 'NIST800 - 108 - F',
            self::NIST800108DPI => 'NIST800 - 108 - DPI',
            self::AsymmetricKey => 'Asymmetric Key',
            self::AWSSignatureVersion4 => 'AWS Signature Version 4',
            self::HKDF => 'HKDF',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
