<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum DestroyAction: int
{
    /** 0x00000001 */
    case Unspecified = 1;

    /** 0x00000002 */
    case KeyMaterialDeleted = 2;

    /** 0x00000003 */
    case KeyMaterialShredded = 3;

    /** 0x00000004 */
    case MetaDataDeleted = 4;

    /** 0x00000005 */
    case MetaDataShredded = 5;

    /** 0x00000006 */
    case Deleted = 6;

    /** 0x00000007 */
    case Shredded = 7;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Unspecified => 'Unspecified',
            self::KeyMaterialDeleted => 'Key Material Deleted',
            self::KeyMaterialShredded => 'Key Material Shredded',
            self::MetaDataDeleted => 'Meta Data Deleted',
            self::MetaDataShredded => 'Meta Data Shredded',
            self::Deleted => 'Deleted',
            self::Shredded => 'Shredded',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
