<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum DRBGAlgorithm: int
{
    /** 0x00000001 */
    case Unspecified = 1;

    /** 0x00000002 */
    case DualEC = 2;

    /** 0x00000003 */
    case Hash = 3;

    /** 0x00000004 */
    case HMAC = 4;

    /** 0x00000005 */
    case CTR = 5;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Unspecified => 'Unspecified',
            self::DualEC => 'Dual - EC',
            self::Hash => 'Hash',
            self::HMAC => 'HMAC',
            self::CTR => 'CTR',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
