<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum EncodingOption: int
{
    /** 0x00000001 */
    case NoEncoding = 1;

    /** 0x00000002 */
    case TTLVEncoding = 2;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::NoEncoding => 'No Encoding',
            self::TTLVEncoding => 'TTLV Encoding',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
