<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum HashingAlgorithm: int
{
    /** 0x00000001 */
    case MD2 = 1;

    /** 0x00000002 */
    case MD4 = 2;

    /** 0x00000003 */
    case MD5 = 3;

    /** 0x00000004 */
    case SHA1 = 4;

    /** 0x00000005 */
    case SHA224 = 5;

    /** 0x00000006 */
    case SHA256 = 6;

    /** 0x00000007 */
    case SHA384 = 7;

    /** 0x00000008 */
    case SHA512 = 8;

    /** 0x00000009 */
    case RIPEMD160 = 9;

    /** 0x0000000A */
    case Tiger = 10;

    /** 0x0000000B */
    case Whirlpool = 11;

    /** 0x0000000C */
    case SHA512224 = 12;

    /** 0x0000000D */
    case SHA512256 = 13;

    /** 0x0000000E */
    case SHA3224 = 14;

    /** 0x0000000F */
    case SHA3256 = 15;

    /** 0x00000010 */
    case SHA3384 = 16;

    /** 0x00000011 */
    case SHA3512 = 17;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::MD2 => 'MD2',
            self::MD4 => 'MD4',
            self::MD5 => 'MD5',
            self::SHA1 => 'SHA-1',
            self::SHA224 => 'SHA-224',
            self::SHA256 => 'SHA-256',
            self::SHA384 => 'SHA-384',
            self::SHA512 => 'SHA-512',
            self::RIPEMD160 => 'RIPEMD-160',
            self::Tiger => 'Tiger',
            self::Whirlpool => 'Whirlpool',
            self::SHA512224 => 'SHA-512/224',
            self::SHA512256 => 'SHA-512/256',
            self::SHA3224 => 'SHA-3-224',
            self::SHA3256 => 'SHA-3-256',
            self::SHA3384 => 'SHA-3-384',
            self::SHA3512 => 'SHA-3-512',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
