<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum KeyCompressionType: int
{
    /** 0x00000001 */
    case ECPublicKeyTypeUncompressed = 1;

    /** 0x00000002 */
    case ECPublicKeyTypeX9_62CompressedPrime = 2;

    /** 0x00000003 */
    case ECPublicKeyTypeX9_62CompressedChar2 = 3;

    /** 0x00000004 */
    case ECPublicKeyTypeX9_62Hybrid = 4;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::ECPublicKeyTypeUncompressed => 'EC Public Key Type Uncompressed',
            self::ECPublicKeyTypeX9_62CompressedPrime => 'EC Public Key Type X9.62 Compressed Prime',
            self::ECPublicKeyTypeX9_62CompressedChar2 => 'EC Public Key Type X9.62 Compressed Char2',
            self::ECPublicKeyTypeX9_62Hybrid => 'EC Public Key Type X9.62 Hybrid',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
