<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum KeyWrapType: int
{
    /** 0x00000001 */
    case NotWrapped = 1;

    /** 0x00000002 */
    case AsRegistered = 2;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::NotWrapped => 'Not Wrapped',
            self::AsRegistered => 'As Registered',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
