<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum MaskGenerator: int
{
    /** 0x00000001 */
    case MGF1 = 1;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::MGF1 => 'MGF1',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
