<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum ObjectType: int
{
    /** 0x00000001 */
    case Certificate = 1;

    /** 0x00000002 */
    case SymmetricKey = 2;

    /** 0x00000003 */
    case PublicKey = 3;

    /** 0x00000004 */
    case PrivateKey = 4;

    /** 0x00000005 */
    case SplitKey = 5;

    /** 0x00000006 */
    case Template = 6;

    /** 0x00000007 */
    case SecretData = 7;

    /** 0x00000008 */
    case OpaqueObject = 8;

    /** 0x00000009 */
    case PGPKey = 9;

    /** 0x0000000A */
    case CertificateRequest = 10;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Certificate => 'Certificate',
            self::SymmetricKey => 'Symmetric Key',
            self::PublicKey => 'Public Key',
            self::PrivateKey => 'Private Key',
            self::SplitKey => 'Split Key',
            self::Template => 'Template',
            self::SecretData => 'Secret Data',
            self::OpaqueObject => 'Opaque Object',
            self::PGPKey => 'PGP Key',
            self::CertificateRequest => 'Certificate Request',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
