<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum PaddingMethod: int
{
    /** 0x00000001 */
    case None = 1;

    /** 0x00000002 */
    case OAEP = 2;

    /** 0x00000003 */
    case PKCS5 = 3;

    /** 0x00000004 */
    case SSL3 = 4;

    /** 0x00000005 */
    case Zeros = 5;

    /** 0x00000006 */
    case ANSIX9_23 = 6;

    /** 0x00000007 */
    case ISO10126 = 7;

    /** 0x00000008 */
    case PKCS1V1_5 = 8;

    /** 0x00000009 */
    case X9_31 = 9;

    /** 0x0000000A */
    case PSS = 10;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::None => 'None',
            self::OAEP => 'OAEP',
            self::PKCS5 => 'PKCS5',
            self::SSL3 => 'SSL3',
            self::Zeros => 'Zeros',
            self::ANSIX9_23 => 'ANSI X9.23',
            self::ISO10126 => 'ISO 10126',
            self::PKCS1V1_5 => 'PKCS1 v1.5',
            self::X9_31 => 'X9.31',
            self::PSS => 'PSS',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
