<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum PutFunction: int
{
    /** 0x00000001 */
    case New = 1;

    /** 0x00000002 */
    case Replace = 2;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::New => 'New',
            self::Replace => 'Replace',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
