<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum RecommendedCurve: int
{
    /** 0x00000001 */
    case P192 = 1;

    /** 0x00000002 */
    case K163 = 2;

    /** 0x00000003 */
    case B163 = 3;

    /** 0x00000004 */
    case P224 = 4;

    /** 0x00000005 */
    case K233 = 5;

    /** 0x00000006 */
    case B233 = 6;

    /** 0x00000007 */
    case P256 = 7;

    /** 0x00000008 */
    case K283 = 8;

    /** 0x00000009 */
    case B283 = 9;

    /** 0x0000000A */
    case P384 = 10;

    /** 0x0000000B */
    case K409 = 11;

    /** 0x0000000C */
    case B409 = 12;

    /** 0x0000000D */
    case P521 = 13;

    /** 0x0000000E */
    case K571 = 14;

    /** 0x0000000F */
    case B571 = 15;

    /** 0x00000010 */
    case SECP112R1 = 16;

    /** 0x00000011 */
    case SECP112R2 = 17;

    /** 0x00000012 */
    case SECP128R1 = 18;

    /** 0x00000013 */
    case SECP128R2 = 19;

    /** 0x00000014 */
    case SECP160K1 = 20;

    /** 0x00000015 */
    case SECP160R1 = 21;

    /** 0x00000016 */
    case SECP160R2 = 22;

    /** 0x00000017 */
    case SECP192K1 = 23;

    /** 0x00000018 */
    case SECP224K1 = 24;

    /** 0x00000019 */
    case SECP256K1 = 25;

    /** 0x0000001A */
    case SECT113R1 = 26;

    /** 0x0000001B */
    case SECT113R2 = 27;

    /** 0x0000001C */
    case SECT131R1 = 28;

    /** 0x0000001D */
    case SECT131R2 = 29;

    /** 0x0000001E */
    case SECT163R1 = 30;

    /** 0x0000001F */
    case SECT193R1 = 31;

    /** 0x00000020 */
    case SECT193R2 = 32;

    /** 0x00000021 */
    case SECT239K1 = 33;

    /** 0x00000022 */
    case ANSIX9P192V2 = 34;

    /** 0x00000023 */
    case ANSIX9P192V3 = 35;

    /** 0x00000024 */
    case ANSIX9P239V1 = 36;

    /** 0x00000025 */
    case ANSIX9P239V2 = 37;

    /** 0x00000026 */
    case ANSIX9P239V3 = 38;

    /** 0x00000027 */
    case ANSIX9C2PNB163V1 = 39;

    /** 0x00000028 */
    case ANSIX9C2PNB163V2 = 40;

    /** 0x00000029 */
    case ANSIX9C2PNB163V3 = 41;

    /** 0x0000002A */
    case ANSIX9C2PNB176V1 = 42;

    /** 0x0000002B */
    case ANSIX9C2TNB191V1 = 43;

    /** 0x0000002C */
    case ANSIX9C2TNB191V2 = 44;

    /** 0x0000002D */
    case ANSIX9C2TNB191V3 = 45;

    /** 0x0000002E */
    case ANSIX9C2PNB208W1 = 46;

    /** 0x0000002F */
    case ANSIX9C2TNB239V1 = 47;

    /** 0x00000030 */
    case ANSIX9C2TNB239V2 = 48;

    /** 0x00000031 */
    case ANSIX9C2TNB239V3 = 49;

    /** 0x00000032 */
    case ANSIX9C2PNB272W1 = 50;

    /** 0x00000033 */
    case ANSIX9C2PNB304W1 = 51;

    /** 0x00000034 */
    case ANSIX9C2TNB359V1 = 52;

    /** 0x00000035 */
    case ANSIX9C2PNB368W1 = 53;

    /** 0x00000036 */
    case ANSIX9C2TNB431R1 = 54;

    /** 0x00000037 */
    case BRAINPOOLP160R1 = 55;

    /** 0x00000038 */
    case BRAINPOOLP160T1 = 56;

    /** 0x00000039 */
    case BRAINPOOLP192R1 = 57;

    /** 0x0000003A */
    case BRAINPOOLP192T1 = 58;

    /** 0x0000003B */
    case BRAINPOOLP224R1 = 59;

    /** 0x0000003C */
    case BRAINPOOLP224T1 = 60;

    /** 0x0000003D */
    case BRAINPOOLP256R1 = 61;

    /** 0x0000003E */
    case BRAINPOOLP256T1 = 62;

    /** 0x0000003F */
    case BRAINPOOLP320R1 = 63;

    /** 0x00000040 */
    case BRAINPOOLP320T1 = 64;

    /** 0x00000041 */
    case BRAINPOOLP384R1 = 65;

    /** 0x00000042 */
    case BRAINPOOLP384T1 = 66;

    /** 0x00000043 */
    case BRAINPOOLP512R1 = 67;

    /** 0x00000044 */
    case BRAINPOOLP512T1 = 68;

    /** 0x00000045 */
    case CURVE25519 = 69;

    /** 0x00000046 */
    case CURVE448 = 70;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::P192 => 'P-192',
            self::K163 => 'K-163',
            self::B163 => 'B-163',
            self::P224 => 'P-224',
            self::K233 => 'K-233',
            self::B233 => 'B-233',
            self::P256 => 'P-256',
            self::K283 => 'K-283',
            self::B283 => 'B-283',
            self::P384 => 'P-384',
            self::K409 => 'K-409',
            self::B409 => 'B-409',
            self::P521 => 'P-521',
            self::K571 => 'K-571',
            self::B571 => 'B-571',
            self::SECP112R1 => 'SECP112R1',
            self::SECP112R2 => 'SECP112R2',
            self::SECP128R1 => 'SECP128R1',
            self::SECP128R2 => 'SECP128R2',
            self::SECP160K1 => 'SECP160K1',
            self::SECP160R1 => 'SECP160R1',
            self::SECP160R2 => 'SECP160R2',
            self::SECP192K1 => 'SECP192K1',
            self::SECP224K1 => 'SECP224K1',
            self::SECP256K1 => 'SECP256K1',
            self::SECT113R1 => 'SECT113R1',
            self::SECT113R2 => 'SECT113R2',
            self::SECT131R1 => 'SECT131R1',
            self::SECT131R2 => 'SECT131R2',
            self::SECT163R1 => 'SECT163R1',
            self::SECT193R1 => 'SECT193R1',
            self::SECT193R2 => 'SECT193R2',
            self::SECT239K1 => 'SECT239K1',
            self::ANSIX9P192V2 => 'ANSIX9P192V2',
            self::ANSIX9P192V3 => 'ANSIX9P192V3',
            self::ANSIX9P239V1 => 'ANSIX9P239V1',
            self::ANSIX9P239V2 => 'ANSIX9P239V2',
            self::ANSIX9P239V3 => 'ANSIX9P239V3',
            self::ANSIX9C2PNB163V1 => 'ANSIX9C2PNB163V1',
            self::ANSIX9C2PNB163V2 => 'ANSIX9C2PNB163V2',
            self::ANSIX9C2PNB163V3 => 'ANSIX9C2PNB163V3',
            self::ANSIX9C2PNB176V1 => 'ANSIX9C2PNB176V1',
            self::ANSIX9C2TNB191V1 => 'ANSIX9C2TNB191V1',
            self::ANSIX9C2TNB191V2 => 'ANSIX9C2TNB191V2',
            self::ANSIX9C2TNB191V3 => 'ANSIX9C2TNB191V3',
            self::ANSIX9C2PNB208W1 => 'ANSIX9C2PNB208W1',
            self::ANSIX9C2TNB239V1 => 'ANSIX9C2TNB239V1',
            self::ANSIX9C2TNB239V2 => 'ANSIX9C2TNB239V2',
            self::ANSIX9C2TNB239V3 => 'ANSIX9C2TNB239V3',
            self::ANSIX9C2PNB272W1 => 'ANSIX9C2PNB272W1',
            self::ANSIX9C2PNB304W1 => 'ANSIX9C2PNB304W1',
            self::ANSIX9C2TNB359V1 => 'ANSIX9C2TNB359V1',
            self::ANSIX9C2PNB368W1 => 'ANSIX9C2PNB368W1',
            self::ANSIX9C2TNB431R1 => 'ANSIX9C2TNB431R1',
            self::BRAINPOOLP160R1 => 'BRAINPOOLP160R1',
            self::BRAINPOOLP160T1 => 'BRAINPOOLP160T1',
            self::BRAINPOOLP192R1 => 'BRAINPOOLP192R1',
            self::BRAINPOOLP192T1 => 'BRAINPOOLP192T1',
            self::BRAINPOOLP224R1 => 'BRAINPOOLP224R1',
            self::BRAINPOOLP224T1 => 'BRAINPOOLP224T1',
            self::BRAINPOOLP256R1 => 'BRAINPOOLP256R1',
            self::BRAINPOOLP256T1 => 'BRAINPOOLP256T1',
            self::BRAINPOOLP320R1 => 'BRAINPOOLP320R1',
            self::BRAINPOOLP320T1 => 'BRAINPOOLP320T1',
            self::BRAINPOOLP384R1 => 'BRAINPOOLP384R1',
            self::BRAINPOOLP384T1 => 'BRAINPOOLP384T1',
            self::BRAINPOOLP512R1 => 'BRAINPOOLP512R1',
            self::BRAINPOOLP512T1 => 'BRAINPOOLP512T1',
            self::CURVE25519 => 'CURVE25519',
            self::CURVE448 => 'CURVE448',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
