<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum ResultStatus: int
{
    /** 0x00000000 */
    case Success = 0;

    /** 0x00000001 */
    case OperationFailed = 1;

    /** 0x00000002 */
    case OperationPending = 2;

    /** 0x00000003 */
    case OperationUndone = 3;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Success => 'Success',
            self::OperationFailed => 'Operation Failed',
            self::OperationPending => 'Operation Pending',
            self::OperationUndone => 'Operation Undone',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
