<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum RevocationReasonCode: int
{
    /** 0x00000001 */
    case Unspecified = 1;

    /** 0x00000002 */
    case KeyCompromise = 2;

    /** 0x00000003 */
    case CACompromise = 3;

    /** 0x00000004 */
    case AffiliationChanged = 4;

    /** 0x00000005 */
    case Superseded = 5;

    /** 0x00000006 */
    case CessationOfOperation = 6;

    /** 0x00000007 */
    case PrivilegeWithdrawn = 7;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Unspecified => 'Unspecified',
            self::KeyCompromise => 'Key Compromise',
            self::CACompromise => 'CA Compromise',
            self::AffiliationChanged => 'Affiliation Changed',
            self::Superseded => 'Superseded',
            self::CessationOfOperation => 'Cessation of Operation',
            self::PrivilegeWithdrawn => 'Privilege Withdrawn',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
