<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum RNGAlgorithm: int
{
    /** 0x00000001 */
    case Unspecified = 1;

    /** 0x00000002 */
    case FIPS1862 = 2;

    /** 0x00000003 */
    case DRBG = 3;

    /** 0x00000004 */
    case NRBG = 4;

    /** 0x00000005 */
    case ANSIX9_31 = 5;

    /** 0x00000006 */
    case ANSIX9_62 = 6;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Unspecified => 'Unspecified',
            self::FIPS1862 => 'FIPS 186-2',
            self::DRBG => 'DRBG',
            self::NRBG => 'NRBG',
            self::ANSIX9_31 => 'ANSI X9.31',
            self::ANSIX9_62 => 'ANSI X9.62',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
