<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum ShreddingAlgorithm: int
{
    /** 0x00000001 */
    case Unspecified = 1;

    /** 0x00000002 */
    case Cryptographic = 2;

    /** 0x00000003 */
    case Unsupported = 3;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Unspecified => 'Unspecified',
            self::Cryptographic => 'Cryptographic',
            self::Unsupported => 'Unsupported',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
