<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum SplitKeyMethod: int
{
    /** 0x00000001 */
    case XOR = 1;

    /** 0x00000002 */
    case PolynomialSharingGF2_16 = 2;

    /** 0x00000003 */
    case PolynomialSharingPrimeField = 3;

    /** 0x00000004 */
    case PolynomialSharingGF2_8 = 4;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::XOR => 'XOR',
            self::PolynomialSharingGF2_16 => 'Polynomial Sharing GF (2^16)',
            self::PolynomialSharingPrimeField => 'Polynomial Sharing Prime Field',
            self::PolynomialSharingGF2_8 => 'Polynomial Sharing GF (2^8)',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
