<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum State: int
{
    /** 0x00000001 */
    case PreActive = 1;

    /** 0x00000002 */
    case Active = 2;

    /** 0x00000003 */
    case Deactivated = 3;

    /** 0x00000004 */
    case Compromised = 4;

    /** 0x00000005 */
    case Destroyed = 5;

    /** 0x00000006 */
    case DestroyedCompromised = 6;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::PreActive => 'Pre-Active',
            self::Active => 'Active',
            self::Deactivated => 'Deactivated',
            self::Compromised => 'Compromised',
            self::Destroyed => 'Destroyed',
            self::DestroyedCompromised => 'Destroyed Compromised',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
