<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum UsageLimitsUnit: int
{
    /** 0x00000001 */
    case Byte = 1;

    /** 0x00000002 */
    case Object = 2;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Byte => 'Byte',
            self::Object => 'Object',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
