<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum ValidationType: int
{
    /** 0x00000001 */
    case Unspecified = 1;

    /** 0x00000002 */
    case Hardware = 2;

    /** 0x00000003 */
    case Software = 3;

    /** 0x00000004 */
    case Firmware = 4;

    /** 0x00000005 */
    case Hybrid = 5;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Unspecified => 'Unspecified',
            self::Hardware => 'Hardware',
            self::Software => 'Software',
            self::Firmware => 'Firmware',
            self::Hybrid => 'Hybrid',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
