<?php

/**
 * DO NOT EDIT. This file is auto-generated by stoakes/kmip-php code generator
 */

declare(strict_types=1);

namespace Stoakes\Kmip\Enum;

enum ValidityIndicator: int
{
    /** 0x00000001 */
    case Valid = 1;

    /** 0x00000002 */
    case Invalid = 2;

    /** 0x00000003 */
    case Unknown = 3;

    public function valueToCanonicalName(self $value): string
    {
        return match($value) {
            self::Valid => 'Valid',
            self::Invalid => 'Invalid',
            self::Unknown => 'Unknown',
        };
    }

    public function canonicalName(): string
    {
        return self::valueToCanonicalName($this);
    }
}
